CREATE OR REPLACE TABLE wallets (
    id BINARY(16) NOT NULL PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    owner_id BINARY(16) NOT NULL,
    money DECIMAL(38,0) UNSIGNED NOT NULL
) CHARACTER SET utf8;
